# Generated by Django 3.0.2 on 2020-01-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='parent_comment',
        ),
    ]
